import numpy as np
v = np.array([1, 2, 3, 4, 5])

print(v - 1)
print(v * 5)
print(v / 5)
print(v*5/10 - 1)
print(np.subtract(v, 1))
print(np.add(v, 1))
print(np.multiply(v,4))
print(np.divide(v, 3))
print(v**2)
print(v**3)
print(np.power(v, 3))
print(v % 2)
print(np.mod(v, 2))
print(np.absolute(np.array([-3])))
print(np.sin(360))
print(np.cos(180))

v = np.array([1,2,3])
print(np.log(v))
print(np.log2(v))
print(np.log10(v))
