import numpy as np
v = np.array([1, 2, 3, 4, 5])
print(v < 3)
print(v[v < 3])
print(v[v > 3])
print(v[v >= 3])
print(v[v <= 3])
print(v[v == 3])
print(v[v != 3])
print(v)
print(v * 2)
print(v / 5)
print(v*5/10)
print(v**2)
